/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.magi.fastbi.jframes.distribuidores;

import cl.magi.fastbi.dao.DistribuidorService;
import cl.magi.fastbi.dto.Distribuidor;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class borrarDistribuidorFrame extends javax.swing.JFrame {

    /**
     * Creates new form borrarDistribuidorFrame
     */
    public borrarDistribuidorFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rutDistTxt = new javax.swing.JTextField();
        eliminarDistBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Rut Distribuidor:");

        rutDistTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rutDistTxtActionPerformed(evt);
            }
        });

        eliminarDistBtn.setText("Eliminar");
        eliminarDistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarDistBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarDistBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rutDistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rutDistTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(eliminarDistBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rutDistTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutDistTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutDistTxtActionPerformed

    private void eliminarDistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarDistBtnActionPerformed
        try {
            List<Distribuidor> distribuidores = new DistribuidorService().obtenerDist();
            String id = rutDistTxt.getText();
            boolean a = false;
            for (Distribuidor es : distribuidores) {
                if (es.getRutDist().equals(id)) {
                    a = true;
                    if (new DistribuidorService().eliminarDist(id)) {
                        JOptionPane.showMessageDialog(this, "Distribuidor con Rut: " + id + "ha sido eliminado", "Borrado", JOptionPane.INFORMATION_MESSAGE);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al eliminar el Distribuidor", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }
            }
            if (!a) {
                JOptionPane.showMessageDialog(this, "Distribuidor no existe", "Error", JOptionPane.ERROR_MESSAGE);
            }
            rutDistTxt.setText("");           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ingrese un Rut valido", "Error", JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_eliminarDistBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.rutDistTxt.setText("");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eliminarDistBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField rutDistTxt;
    // End of variables declaration//GEN-END:variables
}
