/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.magi.fastbi.jframes.autor;

import cl.magi.fastbi.dao.AutorService;
import cl.magi.fastbi.dto.Autor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jmfix
 */
public class MostrarAutorFrame extends javax.swing.JFrame {

    /**
     * Creates new form MostrarAutorFrame
     */
    public MostrarAutorFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    Autor autor;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActualizarAutorBtn = new javax.swing.JButton();
        CboAutorEliminar = new javax.swing.JComboBox<>();
        EliminarAutorBtn = new javax.swing.JButton();
        NomAutroTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ApePatAutorTxt = new javax.swing.JTextField();
        ApeMatAutorTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IdAutorTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblAutor = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ActualizarAutorBtn.setText("Actualizar");
        ActualizarAutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarAutorBtnActionPerformed(evt);
            }
        });

        EliminarAutorBtn.setText("Eliminar");
        EliminarAutorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarAutorBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido Paterno");

        jLabel2.setText("Apellido Materno");

        jLabel3.setText("Nombre del Autor");

        jLabel4.setText("Eliminar Autor");

        jLabel5.setText("ID :");

        jtblAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblAutor.setEnabled(false);
        jtblAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblAutorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblAutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(CboAutorEliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NomAutroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApePatAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ApeMatAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IdAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ActualizarAutorBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(EliminarAutorBtn)))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 421, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NomAutroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApePatAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApeMatAutorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(ActualizarAutorBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboAutorEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EliminarAutorBtn)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarFormulario() {
        this.IdAutorTxt.setText("");
        this.NomAutroTxt.setText("");
        this.ApePatAutorTxt.setText("");
        this.ApeMatAutorTxt.setText("");
    }
    
    private void cargarAutorCbx() {
        this.CboAutorEliminar.removeAllItems();
        AutorService autorService = new AutorService();
        List<Autor> autores = autorService.obtenerAutores();
        for (Autor autor : autores) {
            this.CboAutorEliminar.addItem(autor);
        }
    }
    
    private void cargarJtable () {
        DefaultTableModel modelo = new DefaultTableModel();
        List<Autor> autores = new AutorService().obtenerAutores();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre del autor");
        modelo.addColumn("Apellido paterno");
        modelo.addColumn("Apellido materno");
        Object [] fila = new Object[4];
        for (Autor aut : autores) {
            fila[0] = aut.getIdAutor();
            fila[1] = aut.getNombreAutor();
            fila[2] = aut.getApellidoPatAutor();
            fila[3] = aut.getApellidoMatAutor();
            modelo.addRow(fila);
        }
        jtblAutor.setModel(modelo);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        limpiarFormulario();
        cargarAutorCbx();
        cargarJtable();
        
    }//GEN-LAST:event_formWindowOpened

    private void ActualizarAutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarAutorBtnActionPerformed
        // TODO add your handling code here:
        
        autor.setNombreAutor(NomAutroTxt.getText().trim());
        autor.setApellidoPatAutor(ApePatAutorTxt.getText().trim());
        autor.setApellidoMatAutor(ApeMatAutorTxt.getText().trim());

        if (new AutorService().actualizarAutor(autor)) {
            JOptionPane.showMessageDialog(this, "Autor con código " + autor.getIdAutor()
                    + "actualizado correctamente", "Correcto", JOptionPane.INFORMATION_MESSAGE);
            cargarJtable();
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio un error", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_ActualizarAutorBtnActionPerformed

    private void EliminarAutorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarAutorBtnActionPerformed
        // TODO add your handling code here:
        List<Autor> autores = new AutorService().obtenerAutores();
        try {
            int id = Integer.parseInt(CboAutorEliminar.getSelectedItem().toString());
            boolean esta = false;
            for (Autor aut : autores) {
                if (aut.getIdAutor()== id) {
                    esta = true;
                    if (new AutorService().eliminatAutor(id)) {
                        JOptionPane.showMessageDialog(this, "El autor con ID: " + id
                                + "se elimino correctamente", "Borrado", JOptionPane.INFORMATION_MESSAGE);
                        cargarJtable();
                    } else {
                        JOptionPane.showMessageDialog(this, "Hubo un error al borrar el autor", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    break;
                }
            }
            if (!esta) {
                JOptionPane.showMessageDialog(this, "Autor no existente", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar una id valida", "Error de validación", JOptionPane.ERROR_MESSAGE);
        }
        IdAutorTxt.setText("");
    }//GEN-LAST:event_EliminarAutorBtnActionPerformed

    private void jtblAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblAutorMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtblAutorMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarAutorBtn;
    private javax.swing.JTextField ApeMatAutorTxt;
    private javax.swing.JTextField ApePatAutorTxt;
    private javax.swing.JComboBox<Autor> CboAutorEliminar;
    private javax.swing.JButton EliminarAutorBtn;
    private javax.swing.JTextField IdAutorTxt;
    private javax.swing.JTextField NomAutroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtblAutor;
    // End of variables declaration//GEN-END:variables
}
