/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.magi.fastbi.jframes.libros;

import cl.magi.fastbi.dao.LibroService;
import cl.magi.fastbi.dto.Libro;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sistemas
 */
public class mostrarLibrosFrame extends javax.swing.JFrame {

    /**
     * Creates new form mostrarLibrosFrame
     */
    public mostrarLibrosFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtn_mostrarLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbtn_mostrarLibros.setText("Mostrar libros");
        jbtn_mostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_mostrarLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtn_mostrarLibros)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtn_mostrarLibros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jbtn_mostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_mostrarLibrosActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = new DefaultTableModel();
        List<Libro> libros = new LibroService().obtenerLibro();
        
        modelo.addColumn("Código");
        modelo.addColumn("Título");
        modelo.addColumn("ISBN");
        modelo.addColumn("Páginas");
        modelo.addColumn("Precio ref.");
        modelo.addColumn("Año");
        modelo.addColumn("Publicacion");
        modelo.addColumn("Editorial");
        modelo.addColumn("Autor(es)");
        modelo.addColumn("Idioma(s)");
        modelo.addColumn("Categoría(s)");
        
        Object[] fila = new Object[11];
        for(Libro lib : libros){
            fila[0] = lib.getSerialNumber();
            fila[1] = lib.getTituloLibro();
            fila[2] = lib.getIsbnLibro();
            fila[3] = lib.getNumPagLibro();
            fila[4] = lib.getPrecioRefLibro();
            fila[5] = lib.getAnioRefLibro();
            fila[6] = lib.getPublicacionLibro();
            fila[7] = lib.getIdEditorial();
            
        }
    
    }//GEN-LAST:event_jbtn_mostrarLibrosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtn_mostrarLibros;
    // End of variables declaration//GEN-END:variables
}
