/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.magi.fastbi.jframes.libros;

import cl.magi.fastbi.dao.AutorService;
import cl.magi.fastbi.dao.CategoriaService;
import cl.magi.fastbi.dao.EditorialService;
import cl.magi.fastbi.dao.EstadoService;
import cl.magi.fastbi.dao.IdiomaService;
import cl.magi.fastbi.dao.LibroService;
import cl.magi.fastbi.dto.Autor;
import cl.magi.fastbi.dto.Editorial;
import cl.magi.fastbi.dto.Estado;
import cl.magi.fastbi.dto.Idioma;
import cl.magi.fastbi.dto.Libro;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author franc
 */
public class registrarLibroFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarLibro
     */
    public registrarLibroFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ingresarLibroBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        isbnLibroTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tituloLibroTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cantPaginasLibroTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        precioRefLibroTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        anioDeLibroTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pubLibroTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        autoresCbx = new javax.swing.JComboBox<>();
        idiomaCbx = new javax.swing.JComboBox<>();
        editorialCbx = new javax.swing.JComboBox<>();
        estadoCbx = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ingresarLibroBtn.setText("Ingresar");
        ingresarLibroBtn.setToolTipText("");
        ingresarLibroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarLibroBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Registro de Libro");

        jLabel3.setText("ISBN");

        jLabel4.setText("Título");

        jLabel5.setText("Número de páginas");

        jLabel6.setText("Precio referencia");

        jLabel7.setText("Año de");

        jLabel8.setText("Idiomas");

        jLabel9.setText("Publicacion");

        jLabel10.setText("Autores");

        jLabel12.setText("Editorial");

        idiomaCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomaCbxActionPerformed(evt);
            }
        });

        jLabel13.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ingresarLibroBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isbnLibroTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tituloLibroTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cantPaginasLibroTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pubLibroTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(anioDeLibroTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioRefLibroTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(autoresCbx, 0, 288, Short.MAX_VALUE)
                            .addComponent(idiomaCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(editorialCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(isbnLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tituloLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantPaginasLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(precioRefLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anioDeLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idiomaCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pubLibroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(autoresCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorialCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadoCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(ingresarLibroBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarAutorCbx() {
        this.autoresCbx.removeAllItems();
        AutorService autorService = new AutorService();
        List<Autor> autores = autorService.obtenerAutores();
        for (Autor autor : autores) {
            this.autoresCbx.addItem(autor);
        }
    }
    
    private void cargarIdiomaCbx() {
        this.idiomaCbx.removeAllItems();
        IdiomaService idiomaService = new IdiomaService();
        List<Idioma> idiomas = idiomaService.obtenerIdiomas();
        for (Idioma idioma : idiomas) {
            this.idiomaCbx.addItem(idioma);
        }
    }
    
    private void cargarEditCbx() {
        this.editorialCbx.removeAllItems();
        EditorialService editService = new EditorialService();
        List<Editorial> editoriales = editService.obtenerEditoriales();
        for (Editorial editorial : editoriales) {
            this.editorialCbx.addItem(editorial);
        }
    }
    
    private void cargarEstadoCbx(){
        this.estadoCbx.removeAllItems();
        EstadoService estadoService = new EstadoService();
        List<Estado> estados = estadoService.obtenerEstados();
        for (Estado estado: estados) {
            this.estadoCbx.addItem(estado);
        }
    }
    
    private void limpiarFormulario() {
        this.anioDeLibroTxt.setText("");
        this.autoresCbx.setSelectedIndex(0);
        this.cantPaginasLibroTxt.setText("");
        this.editorialCbx.setSelectedIndex(0);
        this.estadoCbx.setSelectedIndex(0);
        this.idiomaCbx.setSelectedIndex(0);
        this.isbnLibroTxt.setText("");
        this.precioRefLibroTxt.setText("");
        this.pubLibroTxt.setText("");
        this.tituloLibroTxt.setText("");
        
    }

    private void ingresarLibroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarLibroBtnActionPerformed
        // TODO add your handling code here:
        try {
            
            
            Libro libro = new Libro();
           
            libro.setIsbnLibro(Integer
                    .parseInt(this.isbnLibroTxt.getText().trim()));
            libro.setNumPagLibro(Integer
                    .parseInt(this.cantPaginasLibroTxt.getText().trim()));
            libro.setPrecioRefLibro(Integer
                    .parseInt(this.precioRefLibroTxt.getText().trim()));
            libro.setAnioRefLibro(this.anioDeLibroTxt.getText().trim());
            libro.setPublicacionLibro(this.pubLibroTxt.getText().trim());
            libro.setTituloLibro(this.tituloLibroTxt.getText().trim());
            libro.setIdEstado(this.estadoCbx.getSelectedIndex());
            libro.setIdEditorial(this.editorialCbx.getSelectedIndex());
            
            LibroService libroService = new LibroService();
            if (libroService.ingresarLibro(libro)) {
                JOptionPane.showMessageDialog(rootPane, "Guerrero Ingresado");
                limpiarFormulario();
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "FAIL");
            }
            
            /*
    private int serialNumber;
    private int isbnLibro;
    private int numPagLibro;
    private int precioRefLibro;
    private String anioRefLibro;
    private String publicacionLibro;
    private String tituloLibro;
    private int idEstado;
    private int idEditorial;
             */
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,
                    "Verifique los datos", "Eror de Validación",
                    JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_ingresarLibroBtnActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        cargarAutorCbx();
        cargarEditCbx();
        cargarIdiomaCbx();
        cargarEstadoCbx();
        

    }//GEN-LAST:event_formWindowOpened

    private void idiomaCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomaCbxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idiomaCbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioDeLibroTxt;
    private javax.swing.JComboBox<Autor> autoresCbx;
    private javax.swing.JTextField cantPaginasLibroTxt;
    private javax.swing.JComboBox<Editorial> editorialCbx;
    private javax.swing.JComboBox<Estado> estadoCbx;
    private javax.swing.JComboBox<Idioma> idiomaCbx;
    private javax.swing.JToggleButton ingresarLibroBtn;
    private javax.swing.JTextField isbnLibroTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField precioRefLibroTxt;
    private javax.swing.JTextField pubLibroTxt;
    private javax.swing.JTextField tituloLibroTxt;
    // End of variables declaration//GEN-END:variables
}
